config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  namespace :admin do
    resources :plans
    resources :addons
    resources :configurations, only: :index
    namespace :configurations do
      resources :vehicle_makes
      resources :vehicle_models
      resources :category_types
      resources :categories
      resources :vehicle_options, except: [:show, :new]
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'

  resources :subscriptions, only: [:index, :new, :create, :destroy]
  resources :plans, only: :index

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: 'users/registrations' }
  devise_for :admins, :skip => :registrations, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { sessions: "admin/sessions", passwords: "admin/passwords" }

  

  root 'home#index'
  match "*path", :to => "application#routing_error", :via => :all

end

app/models/vehicle_make.rb
class VehicleMake < ActiveRecord::Base
  acts_as_paranoid
  has_many :vehicles
  has_many :vehicle_models, dependent: :destroy
  
  validates_presence_of :name
  validates_uniqueness_of :name
  scope :published, -> { where(published: true) }

end

app/controllers/admin/configurations/categories_controller.rb
class Admin::Configurations::CategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  layout 'configuration'	

  def index
    @categories = Category.all
  end

  def new
  	@category = Category.new
  	@category_types = CategoryType.all
  end

  def edit
  	@category_types = CategoryType.all
  end

  def create
  	@category = Category.new category_params.merge(published: true)
  	if @category.save
  	  flash[:notice] = "Category '#{@category.name}' successfully created.."
  	  redirect_to admin_configurations_categories_path
  	else
  		@category_types = CategoryType.all
  	  flash[:alert] = @category.errors.full_messages.join("<br/>")
  	  render :new
  	end
  end

  def update
    if @category.update_attributes category_params
      flash[:notice] = "Category updated successfully."
      redirect_to admin_configurations_categories_path
    else
      flash[:alert] = @category.errors.full_messages.join(",")
      render :edit
    end
  end

  def destroy
  	if @category.destroy
      flash[:notice] = "Category '#{@category.name}' successfully deleted.."
  	else
  	  flash[:alert] = "Category '#{@category.name}' was not deleted successfully.."
  	end
  	redirect_to admin_configurations_categories_path
  end

  private
  
  def category_params
    params.require(:category).permit(:name, :published, :category_alias, :category_type_id, :avatar, :description)
  end

  def set_category
  	@category = Category.where(id: params[:id]).first
    redirect_to admin_configurations_categories_path, alert: "Requested Category does not exists.." if @category.blank?  
  end

end

app/controllers/admin/configurations/category_types_controller.rb
class Admin::Configurations::CategoryTypesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_category_type, only: [:show, :edit, :update, :destroy]
  layout 'configuration'	

  def index
    @category_types = CategoryType.all
    @category_type = CategoryType.new
  end

  def edit
  end

  def create
  	@category_type = CategoryType.new category_type_params.merge(published: true)
  	if @category_type.save
  	  flash[:notice] = "Category Type '#{@category_type.name}' successfully created.."
  	else
  	  flash[:alert] = @category_type.errors.full_messages.join(",")
  	end
    redirect_to admin_configurations_category_types_path
  end

  def update
    if @category_type.update_attributes category_type_params
      flash[:notice] = "Category Type updated successfully."
      redirect_to admin_configurations_category_types_path
    else
      flash[:alert] = @category_type.errors.full_messages.join(",")
      render :edit
    end
  end

  def destroy
  	if @category_type.destroy
      flash[:notice] = "Category Type '#{@category_type.name}' successfully deleted.."
  	else
  	  flash[:alert] = "Category Type '#{@category_type.name}' was not deleted successfully.."
  	end
  	redirect_to admin_configurations_category_types_path
  end

  private
  
  def category_type_params
    params.require(:category_type).permit(:name, :published)
  end

  def set_category_type
  	@category_type = CategoryType.where(id: params[:id]).first
    redirect_to admin_configurations_category_types_path, alert: "Requested Category Type does not exists.." if @category_type.blank?  
  end


end

app/controllers/admin/configurations/vehicle_makes_controller.rb
class Admin::Configurations::VehicleMakesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_vehicle_make, only: [:show, :edit, :update, :destroy]
  layout 'configuration'	

  def index
    @vehicle_make  = VehicleMake.new
    @vehicle_model = VehicleModel.new
    @vehicle_makes = VehicleMake.all
    @vehicle_models = VehicleModel.all
  end

  def edit
  end

  def create
  	vehicle_make = VehicleMake.new vehicle_make_params.merge(published: true)
  	if vehicle_make.save
  	  flash[:notice] = "Vehicle Make '#{vehicle_make.name}' successfully created.."
  	else
  	  flash[:alert] = vehicle_make.errors.full_messages.join(",")
  	end
  	redirect_to admin_configurations_vehicle_makes_path
  end

  def update
    if @vehicle_make.update_attributes(vehicle_make_params)
      flash[:notice] = "Make updated successfully."
      redirect_to admin_configurations_vehicle_makes_path
    else
      flash[:alert] = @vehicle_make.errors.full_messages.join(",")
      render :edit
    end
  end

  def destroy
  	if @vehicle_make.destroy
      flash[:notice] = "Vehicle Makes '#{@vehicle_make.name}' successfully deleted.."
  	else
  	  flash[:alert] = "Vehicle Makes '#{@vehicle_make.name}' was not deleted successfully.."
  	end
  	redirect_to admin_configurations_vehicle_makes_path
  end

  private
  
  def vehicle_make_params
    params.require(:vehicle_make).permit(:name, :published)
  end

  def set_vehicle_make
  	@vehicle_make = VehicleMake.where(id: params[:id]).first
    redirect_to admin_configurations_vehicle_makes_path, alert: "Requested Vehicle Makes does not exists.." if @vehicle_make.blank?  
  end

end

app/controllers/admin/configurations/vehicle_models_controller.rb
class Admin::Configurations::VehicleModelsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_vehicle_model, only: [:show, :edit, :update, :destroy]
  layout 'configuration'	

  def edit
    @vehicle_makes = VehicleMake.all
  end

  def create
  	vehicle_model = VehicleModel.new vehicle_model_params.merge(published: true)
  	if vehicle_model.save
  	  flash[:notice] = "Vehicle Model '#{vehicle_model.name}' successfully created.."
  	else
  	  flash[:alert] = vehicle_model.errors.full_messages.join(",")
  	end
  	redirect_to admin_configurations_vehicle_makes_path
  end

  def update
    if @vehicle_model.update_attributes(vehicle_model_params)
      flash[:notice] = "Model updated successfully."
      redirect_to admin_configurations_vehicle_makes_path
    else
      flash[:alert] = @vehicle_model.errors.full_messages.join(",")
      render :edit
    end
  end

  def destroy
  	if @vehicle_model.destroy
      flash[:notice] = "Vehicle Model '#{@vehicle_model.name}' successfully deleted.."
  	else
  	  flash[:alert] = "Vehicle Model '#{@vehicle_model.name}' did not deleted successfully.."
  	end
  	redirect_to admin_configurations_vehicle_makes_path
  end

  private
  
  def vehicle_model_params
    params.require(:vehicle_model).permit(:name, :published, :vehicle_make_id)
  end

  def set_vehicle_model
  	@vehicle_model = VehicleModel.where(id: params[:id]).first
    redirect_to admin_configurations_vehicle_makes_path, alert: "Requested Vehicle Model does not exists.." if @vehicle_model.blank?  
  end
end

app/controllers/admin/configurations/vehicle_options_controller.rb
class Admin::Configurations::VehicleOptionsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_vehicle_option, only: [:edit, :update, :destroy]
  layout 'configuration'	

  def index
    @vehicle_options = VehicleOption.all
    @vehicle_option  = VehicleOption.new
  end

  def edit
  end

  def create
  	@vehicle_option = VehicleOption.new vehicle_option_params.merge(published: true)
  	if @vehicle_option.save
  	  flash[:notice] = "Vehicle Option '#{@vehicle_option.name}' successfully created.."
  	else
  	  flash[:alert] = @vehicle_option.errors.full_messages.join(",")
  	end
    redirect_to admin_configurations_vehicle_options_path
  end

  def update
    if @vehicle_option.update_attributes vehicle_option_params
      flash[:notice] = "Vehicle Option updated successfully."
      redirect_to admin_configurations_vehicle_options_path
    else
      flash[:alert] = @vehicle_option.errors.full_messages.join(",")
      render :edit
    end
  end

  def destroy
  	if @vehicle_option.destroy
      flash[:notice] = "Vehicle Option '#{@vehicle_option.name}' successfully deleted.."
  	else
  	  flash[:alert] = "Vehicle Option '#{@vehicle_option.name}' was not deleted successfully.."
  	end
  	redirect_to admin_configurations_vehicle_options_path
  end

  private
  
  def vehicle_option_params
    params.require(:vehicle_option).permit(:name, :published)
  end

  def set_vehicle_option
  	@vehicle_option = VehicleOption.where(id: params[:id]).first
    redirect_to admin_configurations_vehicle_options_path, alert: "Requested Vehicle Option does not exists.." if @vehicle_option.blank?  
  end

end

app/controllers/admin/configurations_controller.rb
class Admin::ConfigurationsController < ApplicationController
  before_action :authenticate_admin!
  layout 'configuration'
  
  def index
  end

end

app/helpers/admin/configurations/categories_helper.rb
module Admin::Configurations::CategoriesHelper
end

app/helpers/admin/configurations/category_types_helper.rb
module Admin::Configurations::CategoryTypesHelper
end

app/helpers/admin/configurations/vehicle_makes_helper.rb
module Admin::Configurations::VehicleMakesHelper
end

app/helpers/admin/configurations/vehicle_models_helper.rb
module Admin::Configurations::VehicleModelsHelper
end

app/helpers/admin/configurations/vehicle_options_helper.rb
module Admin::Configurations::VehicleOptionsHelper
end

app/helpers/admin/configurations_helper.rb
module Admin::ConfigurationsHelper
end

app/views/admin/configurations/vehicle_makes/_makes_and_models.html.erb
<div class="row">
  <div class="col-md-6">
    <table class="table">
      <thead>
        <tr>
          <th>Makes Name</th>
          <th>Published</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @vehicle_makes.each do |make| %>
          <tr>
            <td> <%= make.name %> </td>
            <td> <%= make.published ? "Yes" : "No" %> </td>
            <td>
              <%= link_to "Edit", edit_admin_configurations_vehicle_make_path(make), class: "btn btn-primary" %> 
              <%= link_to "Remove", admin_configurations_vehicle_make_path(make), method: :delete, data: {confirm: "Are you sure to delete this make?"}, class: "btn btn-danger" %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-md-6">
    <table class="table">
      <thead>
        <tr>
          <th>Models Name</th>
          <th>Make Name</th>
          <th>Published</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @vehicle_models.each do |vehicle_model| %>
          <tr>
            <td> <%= vehicle_model.name %> </td>
            <td> <%= vehicle_model.vehicle_make.name %> </td>
            <td> <%= vehicle_model.published ? "Yes" : "No" %> </td>
            <td>
              <%= link_to "Edit", edit_admin_configurations_vehicle_model_path(vehicle_model), class: "btn btn-primary" %>  
              <%= link_to "Remove", admin_configurations_vehicle_model_path(vehicle_model), method: :delete, data: {confirm: "Are you sure to delete this Model?"}, class: "btn btn-danger" %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>  
</div>

app/views/admin/configurations/vehicle_makes/edit.html.erb
<h1>Admin::Configurations::VehicleMakes#edit</h1>
<p>Find me in app/views/admin/configurations/vehicle_makes/edit.html.erb</p>

app/views/admin/configurations/vehicle_makes/index.html.erb
<%= render partial: 'makes_and_models' %>
<div class="row">
  <div class="col-md-6">
    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
      Add a make to the database.
    </a>
    <div id="collapseOne" class="accordion-body collapse in">
      <div class="accordion-inner">
        <%= form_for @vehicle_make, url: admin_configurations_vehicle_makes_path, method: :post do |f| %>
          <%= f.text_field :name, placeholder: "Please type makes name" %>
          <%= f.submit "Create Makes", class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
      Add a model to the database.
    </a>

    <div id="collapseOne" class="accordion-body collapse in">
      <div class="accordion-inner">
        <%= form_for @vehicle_model, url: admin_configurations_vehicle_models_path, method: :post do |f| %>
          <%= f.select :vehicle_make_id, options_for_select(@vehicle_makes.collect{|v| [v.name, v.id]}), {}, {class: "selectpicker"} %>
          <%= f.text_field :name, placeholder: "Please type model name" %>
          <%= f.submit "Create Models", class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/configurations/vehicle_makes/new.html.erb
<h1>Admin::Configurations::VehicleMakes#new</h1>
<p>Find me in app/views/admin/configurations/vehicle_makes/new.html.erb</p>