config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  namespace :admin do
    resources :plans
    resources :addons
    resources :configurations, only: :index
    namespace :configurations do
      resources :vehicle_makes
      resources :vehicle_models
      resources :category_types
      resources :categories
      resources :vehicle_options, except: [:show, :new]
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'

  resources :subscriptions, only: [:index, :new, :create, :destroy]
  resources :plans, only: :index

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: 'users/registrations' }
  devise_for :admins, :skip => :registrations, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { sessions: "admin/sessions", passwords: "admin/passwords" }

  

  root 'home#index'
  match "*path", :to => "application#routing_error", :via => :all

end

app/views/shared/_configuration_header.html.erb
<div class="icon">
  <a href="<%= admin_configurations_path %>">
    <img src="http://nvmedia.com.au/administrator/components/com_rdautos/labels/home.png" border="0" alt="Needs a Value!" style="width:55px;"> 
    <span class="small">Control Panel</span>
  </a>
</div>                
 
<div class="icon">
  <a href="">
    <img src="http://nvmedia.com.au/administrator/components/com_rdautos/labels/vehicles.png" border="0" alt="Needs a Value!" style="width:55px;"> 
    <span class="small" style="padding-top: 5px;">Vehicles</span>
  </a>
</div>         

<div class="icon">
  <a href="<%= admin_configurations_category_types_path %>">
    <img src="http://nvmedia.com.au/administrator/components/com_rdautos/labels/categories.png" border="0" alt="Needs a Value!" style="width:55px;"> 
    <span class="small" style="padding-top: 5px;">Category Type</span>
  </a>
</div> 

<div class="icon">
  <a href="<%= admin_configurations_categories_path %>">
    <img src="http://nvmedia.com.au/administrator/components/com_rdautos/labels/categories.png" border="0" alt="Needs a Value!" style="width:55px;"> 
    <span class="small" style="padding-top: 5px;">Categories</span>
  </a>
</div> 
  
  <div class="icon">
  <a href="<%= admin_configurations_vehicle_makes_path %>">
    <img src="http://nvmedia.com.au/administrator/components/com_rdautos/labels/makesmodels.png" border="0" alt="Needs a Value!" style="width:55px;"> 
    <span class="small" style="padding-top: 5px;">Makes and Models</span>
  </a>
</div>         
  
<div class="icon">
  <a href="<%= admin_configurations_vehicle_options_path %>">
    <img src="http://nvmedia.com.au/administrator/components/com_rdautos/labels/options.png" border="0" alt="Needs a Value!" style="width:55px;"> 
    <span class="small" style="padding-top: 5px;">Vehicle Options</span>
  </a>
</div>        

<div class="icon">
  <a href="">
    <img src="http://nvmedia.com.au/administrator/components/com_rdautos/labels/parts.png" border="0" alt="Needs a Value!" style="width:55px;"> 
    <span class="small" style="padding-top: 5px;">Selling Parts</span>
  </a>
</div>        
  
<div class="icon">
  <a href="">
    <img src="http://nvmedia.com.au/administrator/components/com_rdautos/labels/configuration.png" border="0" alt="Needs a Value!" style="width:55px;"> 
    <span class="small" style="padding-top: 5px;">Configuration</span>
  </a>
</div>
  
<div class="icon">
  <a href="">
    <img src="http://nvmedia.com.au/administrator/components/com_rdautos/labels/dbcheck.png" border="0" alt="Needs a Value!" style="width:55px;"> 
    <span class="small" style="padding-top: 5px;">Database Checker</span>
  </a>
</div>

app/views/shared/_flash_message.html.erb
<script type="text/javascript">
  $(".alert_msg_nav_bar").removeClass("hide"); 
</script>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert_margin margin_flash alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert" id=<%= "dashboard_flash" if @flash_dashboard.present? %>>&#215;</a>
	  <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
	</div>
  <% end %>
  <% flash.discard(name) %>
<% end %>