config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  namespace :admin do
    resources :plans
    resources :addons
    resources :configurations, only: :index
    namespace :configurations do
      resources :vehicle_makes
      resources :vehicle_models
      resources :category_types
      resources :categories
      resources :vehicle_options, except: [:show, :new]
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'

  resources :subscriptions, only: [:index, :new, :create, :destroy]
  resources :plans, only: :index

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: 'users/registrations' }
  devise_for :admins, :skip => :registrations, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { sessions: "admin/sessions", passwords: "admin/passwords" }

  

  root 'home#index'
  match "*path", :to => "application#routing_error", :via => :all

end

app/models/addon.rb
class Addon < ActiveRecord::Base
  acts_as_paranoid
  validates_presence_of :name, :price, :currency

  has_many :subscriptions, :as => :subscriptionable
  has_many :users, through: :subscriptions

  scope :active, -> { where(activated: true) }
  scope :inactive, -> { where(activated: false) }

  before_destroy :update_activation


  private
  def update_activation
    update_attributes(activated: false)
  end
end

app/controllers/admin/addons_controller.rb
class Admin::AddonsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_addon, only: [:show, :edit, :update, :destroy]
  
  def index
  	@active_addons = Addon.active
  	@in_active_addons = Addon.inactive
  end

  def new
  	@addon = Addon.new
  end

  def create
  	@addon = Addon.new(addon_params)
  	if @addon.save
  	  redirect_to admin_addons_path, notice: "Addon successfully created."
  	else
  	  render :new 
  	end
  end


  def edit
  end

  def update
    if @addon.update_attributes(addon_params)
      redirect_to admin_addons_path, notice: "Addon successfully Updated.."
    else
      render :edit
    end
  end

  def destroy
  	addon = Addon.where(id: params[:id]).first
    if addon.destroy
      flash[:notice] = "Addon has been deeted successfully.."
    end
    redirect_to admin_addons_path
  end

  private

  def addon_params
  	params.require(:addon).permit(:name, :price, :currency, :activated)
  end

  def set_addon
    @addon = Addon.where(id: params[:id]).first
    redirect_to admin_addons_path, alert: "Requested Addon does not exists.." if @addon.blank?
  end

end

app/helpers/admin/addons_helper.rb
module Admin::AddonsHelper
end

app/views/admin/addons/edit.html.erb
<h2> Update Addon </h2>

<%= form_for @addon, url: admin_addon_path(@addon), method: :patch do |f| %>
  <%= f.label :name %><br/>
  <%= f.text_field :name %>
  <p class='error'><%= show_errors(@addon, :name) %></p>
  <%= f.label :price %><br/>
  <%= f.text_field :price %>
  <p class='error'><%= show_errors(@addon, :price) %></p>
  <%= f.label :currency %><br/>
  <%= f.text_field :currency %>
  <p class='error'><%= show_errors(@addon, :currency) %></p>
  <%= f.label :activated %><br/>
  <%= f.check_box :activated %><br/>
  <%= f.submit "Update Addon", class: "btn btn-success" %>  
<% end %>

app/views/admin/addons/index.html.erb
<h2>Activated Addons</h2>
<table class="table">
  <thead>
    <tr>
      <th>Addon Name</th>
      <th>Currency</th>
      <th>Amount</th>
      <th>Created Date</th>
      <th>Activated</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @active_addons.each do |addon| %>
      <tr>
        <td> <%= addon.name %> </td>
        <td> <%= addon.currency %> </td>
        <td> $<%= addon.price %> </td>
        <td> <%= addon.created_at.strftime("%d %B %Y   %H:%M") %> </td>
        <td> <%= addon.activated ? "Yes" : "No" %> </td>
        <td>
          <%= link_to "Delete", admin_addon_path(addon), method: :delete, data: {confirm: "Are you sure to remove this Addon"}, class: "btn btn-danger" %> 
           <%= link_to "Edit", edit_admin_addon_path(addon), class: "btn btn-primary" %>
        </td>
      </tr>  
    <% end %>
  </tbody>
</table>


<h2>InActivated Addons</h2>
<table class="table">
  <thead>
    <tr>
      <th>Addon Name</th>
      <th>Currency</th>
      <th>Amount</th>
      <th>Created Date</th>
      <th>Activated</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @in_active_addons.each do |addon| %>
      <tr>
        <td> <%= addon.name %> </td>
        <td> <%= addon.currency %> </td>
        <td> $<%= addon.price %> </td>
        <td> <%= addon.created_at.strftime("%d %B %Y   %H:%M") %> </td>
        <td> <%= addon.activated ? "Yes" : "No" %> </td>
        <td>
          <%= link_to "Delete", admin_addon_path(addon), method: :delete, data: {confirm: "Are you sure to remove this addon"}, class: "btn btn-danger" %>
           <%= link_to "Edit", edit_admin_addon_path(addon), class: "btn btn-primary" %>
        </td>
      </tr>  
    <% end %>
  </tbody>
</table>


<%= link_to "Create New Addon", new_admin_addon_path, class: "btn btn-primary" %>

app/views/admin/addons/new.html.erb
<h2> Create New Addon here </h2>

<%= form_for @addon, url: admin_addons_path, method: :post do |f| %>
  <%= f.label :name %><br/>
  <%= f.text_field :name %>
  <p class='error'><%= show_errors(@addon, :name) %></p>
  <%= f.label :price %><br/>
  <%= f.text_field :price %>
  <p class='error'><%= show_errors(@addon, :price) %></p>
  <%= f.label :currency %><br/>
  <%= f.text_field :currency %>
  <p class='error'><%= show_errors(@addon, :currency) %></p>
  <%= f.label :activated %><br/>
  <%= f.check_box :activated %><br/>
  <%= f.submit "Creat Addon", class: "btn btn-success" %>  
<% end %>